
power_levels = ["apprentice", "journeyman", "expert", "final form"]

base_aspects = ["fire", "water", "earth", "air"]

sub_aspects = {
    "fire": ["lava", "lightning", "combustion", "plasma"],
    "water": ["ice", "swamp", "plant", "blood", "storm"],
    "earth": ["metal", "sand", "mechanical", "strength"],
    "air": ["spirit", "shadow", "psychic", "light"],
}
    

animals = [

    # mammals
    "Cow",
    "Dog",
    "Cat",
    "Horse",
    "Pig",
    "Sheep",
    "Goat",
    "Deer",
    "Bison",
    "Buffalo",
    "Moose",
    "Elk",
    "Donkey",
    "Mule",
    "Zebra",
    "Antelope",
    "Gazelle",
    "Giraffe",
    "Camel",
    "Llama",
    "Alpaca",
    "Kangaroo",
    "Wallaby",
    "Koala",
    "Wombat",
    "Platypus",
    "Echidna",
    "Sloth",
    "Armadillo",
    "Anteater",
    "Beaver",
    "Otter",
    "Seal",
    "Sea Lion",
    "Walrus",
    "Elephant",
    "Rhinoceros",
    "Hippopotamus",
    "Tapir",
    "Aardvark",
    "Hedgehog",
    "Shrew",
    "Mole",
    "Bat",
    "Rat",
    "Mouse",
    "Hamster",
    "Gerbil",
    "Guinea Pig",
    "Capybara",
    "Rabbit",
    "Hare",
    "Squirrel",
    "Chipmunk",
    "Prairie Dog",
    "Marmot",
    "Flying Fox",
    "Lemur",
    "Monkey",
    "Baboon",
    "Chimpanzee",
    "Gorilla",
    "Orangutan",
    "Human",
    "Dolphin",
    "Whale",
    "Orca",
    "Porpoise",
    "Manatee",
    "Dugong",
    "Lion",
    "Tiger",
    "Leopard",
    "Cheetah",
    "Jaguar",
    "Puma",
    "Lynx",
    "Bobcat",
    "Ocelot",
    "Serval",
    "Caracal",
    "Hyena",
    "Wolf",
    "Coyote",
    "Fox",
    "Jackal",
    "Dingo",
    "Fennec Fox",
    "Bear",
    "Panda",
    "Polar Bear",
    "Grizzly Bear",
    "Black Bear",
    "Raccoon",
    "Red Panda",
    "Skunk",
    "Weasel",
    "Mink",
    "Ferret",
    "Badger",
    "Wolverine",
    "Civet",
    "Genet",
    "Meerkat",
    "Mongoose",
    "Otterhound",
    "Chihuahua",
    "Great Dane",
    "Pug",
    "Dalmatian",
    "Beagle",
    "Labrador Retriever",
    "German Shepherd",
    "Border Collie",
    "Siberian Husky",
    "Saint Bernard",
    "Boxer",
    "Greyhound",
    "Whippet",
    "Corgi",
    "Dachshund",
    "Doberman",
    "Mastiff",
    "Rottweiler",
    "Chow Chow",
    "Shar Pei",
    "Bulldog",
    "Pomeranian",
    "Shih Tzu",
    "Maltese",
    "Basset Hound",
    "Akita",
    "Samoyed",
    "Newfoundland",
    "Irish Wolfhound",
    "Poodle",
    "Husky",
    "Golden Retriever",
    "Collie",
    "Terrier",
    "Pekingese",
    "Cat",
    "Lion Cub",
    "Cougar",
    "Snow Leopard",
    "Margay",
    "Fishing Cat",
    "Manul",
    "Clouded Leopard",
    "Elephant Shrew",
    "Rock Hyrax",
    "Tarsier",
    "Slow Loris",
    "Capuchin Monkey",
    "Spider Monkey",
    "Howler Monkey",
    "Marmoset",
    "Gibbon",
    "Bonobo",
    "Aye-aye",
    "Ring-tailed Lemur",
    "Vervet Monkey",
    "Proboscis Monkey",
    "Langur",
    "Colobus Monkey",
    "Patas Monkey",
    "Uakari",
    "Saki Monkey",
    "Bushbaby",
    "Desman",
    "Naked Mole Rat",
    "Tree Shrew",
    "Agouti",
    "Paca",
    "Nutria",
    "Rock Cavy",
    "Chinchilla",
    "Vole",
    "Dormouse",
    "Jerboa",
    "Springhare",
    "Muskrat",
    "Pika",
    "Lemming",
    "Tahr",
    "Ibex",
    "Markhor",
    "Chamois",
    "Saiga Antelope",
    "Dik-dik",
    "Kudu",
    "Eland",
    "Nyala",
    "Waterbuck",
    "Impala",
    "Steenbok",
    "Klipspringer",
    "Roan Antelope",
    "Sitatunga",

    # amphibians and reptiles
    "Crocodile",
    "Alligator",
    "Caiman",
    "Gharial",
    "Komodo Dragon",
    "Iguana",
    "Chameleon",
    "Gecko",
    "Skink",
    "Monitor Lizard",
    "Anole",
    "Basilisk",
    "Snake",
    "Cobra",
    "Python",
    "Boa",
    "Viper",
    "Rattlesnake",
    "Coral Snake",
    "Anaconda",
    "Kingsnake",
    "Milk Snake",
    "Garter Snake",
    "Water Moccasin",
    "Cottonmouth",
    "Sea Snake",
    "Turtle",
    "Tortoise",
    "Sea Turtle",
    "Box Turtle",
    "Snapping Turtle",
    "Terrapin",
    "Frog",
    "Toad",
    "Tree Frog",
    "Poison Dart Frog",
    "Bullfrog",
    "Newt",
    "Salamander",
    "Axolotl",
    "Caecilian",
    "Monitor",
    "Frilled Lizard",
    "Bearded Dragon",
    "Blue-tongued Skink",
    "Flying Dragon",
    "Leopard Gecko",
    "Glass Lizard",
    "Racer Snake",
    "Krait",

    # birds
    "Eagle",
    "Hawk",
    "Falcon",
    "Owl",
    "Vulture",
    "Buzzard",
    "Kite",
    "Osprey",
    "Harrier",
    "Raven",
    "Crow",
    "Magpie",
    "Jay",
    "Rook",
    "Sparrow",
    "Finch",
    "Canary",
    "Parrot",
    "Macaw",
    "Cockatoo",
    "Budgerigar",
    "Lovebird",
    "Pigeon",
    "Dove",
    "Peacock",
    "Turkey",
    "Chicken",
    "Rooster",
    "Duck",
    "Goose",
    "Swan",
    "Flamingo",
    "Pelican",
    "Heron",
    "Stork",
    "Egret",
    "Crane",
    "Ibis",
    "Spoonbill",
    "Hummingbird",
    "Kingfisher",
    "Woodpecker",
    "Toucan",
    "Hornbill",
    "Roadrunner",
    "Kiwi",
    "Ostrich",
    "Emu",
    "Cassowary",
    "Rhea",
    "Penguin",
    "Albatross",
    "Seagull",
    "Puffin",
    "Tern",
    "Petrel",
    "Cormorant",
    "Frigatebird",
    "Booby",
    "Skua",
    "Partridge",
    "Quail",
    "Pheasant",
    "Grouse",
    "Ptarmigan",
    "Guinea Fowl",
    "Cuckoo",
    "Kookaburra",
    "Nightjar",
    "Swallow",
    "Swift",
    "Lark",
    "Wren",
    "Robin",
    "Blackbird",
    "Thrush",
    "Starling",
    "Myna",
    "Mockingbird",
    "Warbler",
    "Bowerbird",
    "Lyrebird",
    "Magellanic Penguin",
    "Bald Eagle",
    "Golden Eagle",
    "Peregrine Falcon",
    "Snowy Owl",
    "Great Horned Owl",
    "Barn Owl",
    "Red-tailed Hawk",
    "Secretary Bird",
    "Shoebill",
    "Cassowary",
    "Raptor Bird",
    "Kestrel",
    "Harpy Eagle",
    "Philippine Eagle",
    "Andean Condor",
    "King Vulture",
    "Turkey Vulture",

    # fish and sea life
    "Goldfish",
    "Koi",
    "Salmon",
    "Trout",
    "Sardine",
    "Anchovy",
    "Flounder",
    "Sole",
    "Catfish",
    "Eel",
    "Anglerfish",
    "Lanternfish",
    "Swordfish",
    "Barracuda",
    "Shark",
    "Great White Shark",
    "Hammerhead Shark",
    "Tiger Shark",
    "Whale Shark",
    "Nurse Shark",
    "Goblin Shark",
    "Manta Ray",
    "Stingray",
    "Seahorse",
    "Pipefish",
    "Clownfish",
    "Lionfish",
    "Butterflyfish",
    "Angelfish",
    "Surgeonfish",
    "Parrotfish",
    "Pufferfish",
    "Goby",
    "Blenny",
    "Tetra",
    "Discus",
    "Cichlid",
    "Zander",
    "Roach",
    "Coelacanth",
    "",
    "",
    "Lamprey",
    "Jellyfish",
    "Sea Urchin",
    "Starfish",
    "Sea Cucumber",
    "Coral",
    "Anemone",
    "Crab",
    "Lobster",
    "Shrimp",
    "Prawn",
    "Krill",
    "Barnacle",
    "Copepod",
    "Isopod",
    "Amphipod",
    "Horseshoe Crab",
    "Sea Spider",
    "Octopus",
    "Squid",
    "Cuttlefish",
    "Nautilus",
    "Clam",
    "Mussel",
    "Oyster",
    "Scallop",
    "Snail",
    "Sea Slug",

    # insects and arthropods
    "Ant",
    "Termite",
    "Bee",
    "Wasp",
    "Hornet",
    "Butterfly",
    "Moth",
    "Caterpillar",
    "Beetle",
    "Ladybug",
    "Firefly",
    "Weevil",
    "Dung Beetle",
    "Rhinoceros Beetle",
    "Stag Beetle",
    "Cockroach",
    "Cricket",
    "Grasshopper",
    "Locust",
    "Katydid",
    "Stick Insect",
    "Leaf Insect",
    "Praying Mantis",
    "Dragonfly",
    "Damselfly",
    "Mosquito",
    "Fly",
    "Horsefly",
    "Fruit Fly",
    "Gnat",
    "Flea",
    "Louse",
    "Tick",
    "Mite",
    "Spider",
    "Tarantula",
    "Scorpion",
    "Centipede",
    "Millipede",
    "Silverfish",
    "Fire Ant",
    "Carpenter Ant",
    "Bumblebee",
    "Carpenter Bee",
    "Yellowjacket",
    "Paper Wasp",
    "Hornet",
    "Velvet Ant",
    "Cicada",
    "Aphid",
    "Lacewing",
    "Earwig",
    "Thrip",
    "Whitefly",
    "Walking Stick",
    "Water Strider",
    "Back Swimmer",
    "Giant Water Bug",
    "Assassin Bug",
    "Bed Bug",
    "Shield Bug",
    "Stink Bug",
    "Beetle Larva",
    "Army Ant",
    "Weaver Ant",
    "Leafcutter Ant",
    "Soldier Termite",
    "Queen Bee",
    "Drone Bee",
    "Worker Bee",
    "Emperor Scorpion",
    "Bark Scorpion",
    "Vinegaroon",
    "Whip Spider",
    "Harvestman",
    "Black Widow",
    "Brown Recluse",
    "Jumping Spider",
    "Wolf Spider",
    "Crab Spider",
    "Orb Weaver",
    "Trapdoor Spider",
    "Funnel-web Spider",
    "Tick Mite",
    "Dust Mite",
    "Tardigrade",
    "Pseudoscorpion",
    "Camel Spider",
    "Solifuge",
    "Centipede",
    "Millipede (African Giant)",
    "Earwig",
    "Booklouse",
    "Bark Beetle",
    "Goliath Beetle",
    "Hercules Beetle",
    "Firefly",
    "Glowworm",
    "Mosquito Larva",

    # extinct / prehistoric
    "Tyrannosaurus Rex",
    "Velociraptor",
    "Triceratops",
    "Stegosaurus",
    "Brachiosaurus",
    "Diplodocus",
    "Allosaurus",
    "Ankylosaurus",
    "Spinosaurus",
    "Pterodactyl",
    "Pteranodon",
    "Archaeopteryx",
    "Mosasaurus",
    "Iguanodon",
    "Parasaurolophus",
    "Pachycephalosaurus",
    "Dilophosaurus",
    "Deinonychus",
    "Utahraptor",
    "Megalosaurus",
    "Oviraptor",
    "Therizinosaurus",
    "Carnotaurus",
    "Cryolophosaurus",
    "Argentinosaurus",
    "Dreadnoughtus",
    "Diplocaulus",
    "Dimetrodon",
    "Smilodon",
    "Woolly Mammoth",
    "Mastodon",
    "Giant Ground Sloth",
    "Dodo",
    "Great Auk",
    "Thylacine",
    "Moa",
    "Megatherium",
    "Megalodon",
    "Plesiosaur",
    "Ichthyosaur",
    "Archaeotherium",
    "Entelodon",
    "Andrewsarchus",
    "Hyaenodon",
    "Terror Bird",
    "Woolly Rhino",
    "Short-faced Bear",
    "Glyptodon",
    "Irish Elk",
    "Passenger Pigeon",

    # misc
    "Axolotl",
    "Coati",
    "Quokka",
    "Quoll",
    "Tasmanian Devil",
    "Pangolin",
    "Okapi",
    "Aardwolf",
    "Fossa",
    "Numbat",
    "Kinkajou",
    "Olingo",
    "Olinguito",
    "Civet Cat",
    "Binturong",
    "Solenodon",
    "Desman",
    "Tenrec",
    "Maned Wolf",
    "Dhole",
    "Saola",
    "Vaquita",
    "Narwhal",
    "Beluga Whale",
    "Dugong",
    "Sun Bear",
    "Spectacled Bear",
    "Andean Cat",
    "Flat-headed Cat",
    "Oncilla",
    "Margay",
    "Sand Cat",
    "Pallas’s Cat",
    "Fishing Cat",
    "Clouded Leopard",
    "Irrawaddy Dolphin",
    "Baiji Dolphin",
    "Indus River Dolphin",
    "Pangolin",
    "Colugo",
    "Flying Squirrel",
    "Sugar Glider",
    "Patagonian Mara",
    "Capuchin",
    "Bush Dog",
    "Maned Rat",
    "Sifaka",
    "Takin",
    "Jerboa",
    "Zorilla",
]

adjectives = [

    # physical
    "Skeletal",
    "Elongated",
    "Bulbous",
    "Jagged",
    "Iridescent",
    "Glossy",
    "Matte",
    "Crystalline",
    "Inflated",
    "Shrunken",
    "Spindly",
    "Compact",
    "Transparent",
    "Luminous",
    "Segmented",
    "Twisted",
    "Knotted",
    "Veined",
    "Faceted",
    "Geometric",

    #"🧠 Personality & Demeanor",
    "Geriatric",
    "Childlike",
    "Cunning",
    "Dopey",
    "Ferocious",
    "Playful",
    "Brooding",
    "Melancholic",
    "Stoic",
    "Chaotic",
    "Mischievous",
    "Obsessive",
    "Loyal",
    "Paranoid",
    "Majestic",
    "Curious",
    "Dreamy",
    "Vengeful",
    "Noble",
    "Timid",
    
    #"⚡️ Structure / Material Quality",
    "Mechanical",
    "Organic",
    "Synthetic",
    "Rusted",
    "Polished",
    "Inflatable",
    "Porous",
    "Brittle",
    "Elastic",
    "Metallic",
    "Gelatinous",
    "Fibrous",
    "Layered",
    "Rigid",
    "Fractured",
    "Seamless",
    "Inflamed",
    "Hollow",
    "Dense",
    "Shattered",

    #"🌫️ Aesthetic or Mystical Vibe",
    "Ethereal",
    "Primal",
    "Spectral",
    "Arcane",
    "Cursed",
    "Blessed",
    "Eldritch",
    "Forgotten",
    "Ancient",
    "Mythic",
    "Sacred",
    "Corrupted",
    "Temporal",
    "Phantasmal",
    "Celestial",
    "Shimmering",
    "Ominous",
    "Radiant",
    "Shadowy",
    "Eternal",
    
    #"🌀 Motion / Behavior",
    "Fluttering",
    "Sluggish",
    "Agile",
    "Erratic",
    "Lurking",
    "Soaring",
    "Crawling",
    "Stalking",
    "Spiraling",
    "Trembling",
    "Burrowing",
    "Floating",
    "Drifting",
    "Skittering",
    "Leaping",
    "Pulsing",
    "Flickering",
    "Vibrating",
    "Phasing",
    "Ascending",
]
